//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Engage.Dnn.SqlServerTypes")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Engage")]
[assembly: AssemblyProduct("Engage.Dnn.SqlServerTypes")]
[assembly: AssemblyVersion("14.0.1016.290")]
[assembly: AssemblyFileVersion("14.0.1016.290")]
[assembly: AssemblyInformationalVersion("14.0.1016.290")]
[assembly: AssemblyCopyright("Copyright © Engage 2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

