//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Engage.Dnn.SqlServerTypes")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Engage")]
[assembly: AssemblyProduct("Engage.Dnn.SqlServerTypes")]
[assembly: AssemblyVersion("160.1000.6")]
[assembly: AssemblyFileVersion("160.1000.6")]
[assembly: AssemblyInformationalVersion("160.1000.6")]
[assembly: AssemblyCopyright("Copyright © Engage 2024")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

